version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    restart: always
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=ggf_db
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"  # Native port
      - "80:8123"  # HTTP port
      - "9009:9009"  # Interserver port
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /media/singhb/Red3/fdsh_panel_app_sample/database:/var/lib/clickhouse

  # panel_app:
  #   image: ghcr.io/balshersingh10/balshersingh10/fdsh_panel_app_sample:latest
  #   container_name: panel_app
  #   restart: always
  #   depends_on:
  #     - clickhouse
  #   ports:
  #     - "80:80"
  #   environment:
  #     - CLICKHOUSE_HOST=clickhouse
  #     - CLICKHOUSE_PORT=9000
  #     - CLICKHOUSE_USER=admin
  #     - CLICKHOUSE_PASSWORD=ggf_db
