version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.1.2.9-alpine
    container_name: clickhouse_server
    restart: always
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=ggf_db
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "80:8123"  # HTTP port
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ${WEBAPP_STORAGE_HOME}/clickhouse_database:/var/lib/clickhouse
