version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.1.2.9-alpine
    container_name: clickhouse_server
    restart: always
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=ggf_db
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8125:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
volumes:
  clickhouse_data:
  clickhouse_logs: